import { library } from '@fortawesome/fontawesome-svg-core'
import {
    faCog,
    faTachometerAlt,
    faBars,
    faUser,
    faFileAlt,
    faBriefcase,
    faAt,
    faHome,
    faGraduationCap,
    faEnvelope,
    faChevronRight,
    faChevronLeft,
    faFilter,
    faArrowUp,
    faArrowDown,
} from '@fortawesome/free-solid-svg-icons'

library.add(
    faCog,
    faTachometerAlt,
    faBars,
    faUser,
    faFileAlt,
    faBriefcase,
    faAt,
    faHome,
    faGraduationCap,
    faEnvelope,
    faChevronRight,
    faChevronLeft,
    faFilter,
    faArrowUp,
    faArrowDown,
)
